### ISSUE TITLE
Created a branch for each of us.

### ISSUE THREAD

**Issue by skistaddy** [bonfire-js/bonfire.js#1]
Just an FYI that I created the branches `baran` and `david`.

**Comment by davidnagli** [comment]
I don't think that really makes sense... wouldn't it be more pragmatic for us to just create feauture branches?

I've never seen anybody use branches with names before, but I could be wrong

**Comment by skistaddy** [comment]
I've done it both ways. The way this way works is:

You have to merge the master branch with your branch to make sure you're up to date. Then, whenever someone makes a PR, we know who made it.

But since we are the only ones working on it, that seems like a lot of work, maybe we should just do your way. :P
